---
title: "CFPB Student Loan Complaints in New England (2020)"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    social: [ "twitter", "facebook", "menu" ]
    theme: united
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(janitor)
library(readxl)
library(writexl)
library(DT)
library(dplyr)
library(ggplot2)
library(bbplot)
library(ggthemes)

complaints <- readRDS("/Users/michaelgraham-green/Downloads/complaints.rds")

complaints_NE <- complaints %>% 
  filter(product == 'Student loan', state == c('MA', 'ME', 'NH', 'VT', 'CT', 'RI')) %>% count(state)

complaints_date <- complaints %>% 
  filter(product == 'Student loan', state == c('MA', 'ME', 'NH', 'VT', 'CT', 'RI')) %>% count(mm_yy_sent_to_company) %>% extract(mm_yy_sent_to_company, c("Month", "2020"), "([[:alnum:]]+) ([[:alnum:]]+)")
```
About
=====================================

### About this Dashboard


Graphs
=====================================

Column {data-width=500}
-----------------------------------------------------------------------

### Breaking Down New England Student Loan Complaints to CFPB by State

<!-- This graph was based on a data frame I made above, filtering for only the New England states and then counting the number of incidents in each state. I made a simple bar graph here to display that data, and chose the Economist theme for the background coloring. -->

```{r}
ggplot2::ggplot(data = complaints_NE, aes(x = state, y = n)) +
    geom_bar(stat = "identity", fill = "#cc0000") +
  geom_text(aes(label=n), position=position_dodge(width=0.9), vjust=-0.25) + 
  labs(title = "Complaints About Student Loans by State",
              subtitle = "2020",
              caption = "Data source: Consumer Financial Protection Bureau",
              x = "State", y = "# of Complaints") +
  theme_economist() 
```

Column {data-width=500}
-----------------------------------------------------------------------

### Timeline of New England Student Loan Complaint Filing Dates

<!-- I created the separate data frame above to separate out the dates complaints were filed, and then break down the date into separate month and year categories. Once I had that new data frame complete, I turned it into a timeline with this graph, although I had to specify the order of the months on the x-axis so that they would not default to alphabetical order. -->

```{r}
ggplot2::ggplot(data = complaints_date, aes(x = factor(Month, level=c('Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')), y = n, group = 1)) +
  geom_line(color="#cc0000") +
  geom_point() + 
  labs(title = "Complaints Over 2020",
              caption = "Data source: Consumer Financial Protection Bureau",
              x = "Month", y = "# of Complaints") +
  theme_economist()
```

Tables {data-orientation=rows}
=====================================

Column {data-width=600}
-----------------------------------------------------------------------
### Breakdown of Complaints by Issue Area

<!-- I filtered student loan issues and New England states and included the designated issue and sub issue in this chart. I also included a count of how many times the same issue occurred. -->

```{r}
DT::datatable((complaints) %>%
  filter(product == 'Student loan', state == c('MA', 'ME', 'NH', 'VT', 'CT', 'RI')) %>% 
  count(issue, sub_issue, sort = TRUE),colnames=c('Issue', 'Subissue','Number of Complaints'), options = list(
  bPaginate = FALSE 
))
```

Column {data-width=400}
-----------------------------------------------------------------------
### Breakdown of Cases by Company Response

```{r}
DT::datatable((complaints) %>%
  filter(product == 'Student loan', state == c('MA', 'ME', 'NH', 'VT', 'CT', 'RI')) %>% 
  count(company_response_to_consumer, sort = TRUE),colnames=c('Company Response To Consumer','Number of Complaints'), options = list(
  bPaginate = FALSE 
))
```

